routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

Route::resource('surat_jalan','SuratJalanController');
Route::resource('surat_jalan_detail','SuratJalanDetailController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/suratJalan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class suratJalan extends Model
{
  protected $fillable = [
  'kode_surat_jalan'
];

public function suratJalanDetail()
{
  return $this->hasMany(\App\suratJalanDetail::class, 'id_surat_jalan');
}

}

app/suratJalanDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class suratJalanDetail extends Model
{
  protected $fillable = [
  'id_surat_jalan',
  'nama_barang',
  'harga_beli',
  'stok'
];

public function suratJalan()
{
  return $this->belongsTo(\App\suratJalan::class, 'id_surat_jalan');
}

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SuratJalanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\suratJalan;
use App\suratJalanDetail;
class SuratJalanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $suratjalan = suratJalan::all();
      $suratjalandetail = suratJalanDetail::all();
      return view('suratJalan',compact('suratjalan', 'suratjalandetail'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $suratjalan = new suratJalan;
      $suratjalan->kode_surat_jalan = $request->get('kode_surat_jalan');
      $suratjalan->save();

      return redirect('surat_jalan');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $sjd = suratJalanDetail::find('id_surat_jalan', '=', $id);
      return view('surat_jalan', [
          "sjd" => $sjd
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/SuratJalanDetailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\suratJalan;
use App\suratJalanDetail;
class SuratJalanDetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $suratjalan = suratJalan::all();
      $suratjalandetail = suratJalandetail::all();
      return view('suratJalanDetail',compact('suratjalan', 'suratjalandetail'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $suratjalandetail = new suratJalanDetail;
      $suratjalandetail->id_surat_jalan = $request->get('kode_surat_jalan');
      $suratjalandetail->nama_barang = $request->get('nama');
      $suratjalandetail->harga_beli = $request->get('harga_beli');
      $suratjalandetail->stok = $request->get('stok');
      $suratjalandetail->save();

      return redirect('surat_jalan_detail');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard.blade.php
@extends('welcome')

@section('content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Dashboard</h1>
</div>
@endsection

resources/views/suratJalan.blade.php
@extends('welcome')

@section('content')
<div class="d-flex">
      <div class="p-2"><h2>Surat Jalan</h2> </div>
      <div class="ml-auto p-2">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal1"><i class="fa fa-plus"></i> Tambah Baru</button>
      </div>
    </div>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>No</th>
        <th>Kode Surat Jalan</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      <?php $no = 0; ?>
         @foreach($suratjalan as $sj)
         <?php $no++; ?>
      <tr>
        <td>{{$no}}</td>
        <td>{{$sj->kode_surat_jalan}}</td>
        <td>
          <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#modal-view{{$sj->id}}">
                      <i class="iconfont fa fa-eye"></i>
                  </button>
              <a data-toggle="modal" data-target="#" href="#">
                  <button class="btn btn-danger btn-sm">
                  <i class="fa fa-trash" aria-hidden="true"></i>
                  </button>
              </a>
        </td>
      </tr>
    </tbody>
    @endforeach
  </table>
  <!-- TAMBAH BARU -->
    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <!-- Change class .modal-sm to change the size of the modal -->
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Tambah Baru</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('surat_jalan.store')}}" method="post" enctype="multipart/form-data" >
                @csrf
            <div class="modal-body mx-3">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="inputAddress">Kode Surat Jalan</label>
                    <input type="text" class="form-control" id="nama" name="kode_surat_jalan">
                  </div>
                </div>
              </div>
            </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success btn-sm">Save changes</button>
          </div>
          </form>
        </div>
      </div>
    </div>
    <!-- TAMBAH BARU  -->

</div>
@endsection

resources/views/suratJalanDetail.blade.php
@extends('welcome')

@section('content')
<div class="d-flex">
      <div class="p-2"><h2>Surat Jalan Detail</h2> </div>
      <div class="ml-auto p-2">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal1"><i class="fa fa-plus"></i> Tambah Baru</button>
      </div>
    </div>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>No</th>
        <th>Kode Surat Jalan</th>
        <th>Nama</th>
        <th>Harga Beli</th>
        <th>Stok</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      <?php $no = 0; ?>
         @foreach($suratjalandetail as $sjd)
         <?php $no++; ?>
      <tr>
        <td>{{$no}}</td>
        <td>{{$sjd->suratJalan->kode_surat_jalan}}</td>
        <td>{{$sjd->nama_barang}}</td>
        <td>{{$sjd->harga_beli}}</td>
        <td>{{$sjd->stok}}</td>
        <td>
          <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#modal-view{{$sjd->id}}">
                      <i class="iconfont fa fa-eye"></i>
                  </button>
              <a data-toggle="modal" data-target="#" href="#">
                  <button class="btn btn-danger btn-sm">
                  <i class="fa fa-trash" aria-hidden="true"></i>
                  </button>
              </a>
        </td>
      </tr>
    </tbody>
    @endforeach
  </table>
  <!-- TAMBAH BARU -->
    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <!-- Change class .modal-sm to change the size of the modal -->
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Tambah Baru</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('surat_jalan_detail.store')}}" method="post" enctype="multipart/form-data" >
                @csrf
            <div class="modal-body mx-3">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="inputAddress">Kode Surat Jalan</label>
                    <select class="browser-default custom-select" name="kode_surat_jalan" style="width:100%;display:block;box-sizing:border-box">
                      <option selected>-- Pilih --</option>
                      @foreach ($suratjalan as $sj)
                        <option value="{{$sj->id}}">{{$sj->kode_surat_jalan}}</option>
                      @endforeach
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="inputAddress">Nama Barang</label>
                    <input type="text" class="form-control" id="kode_surat_jalan" name="nama">
                  </div>
                  <div class="form-group">
                    <label for="inputAddress">Harga Beli</label>
                    <input type="number" class="form-control" id="harga_beli" name="harga_beli">
                  </div>
                  <div class="form-group">
                    <label for="inputAddress">Stok</label>
                    <input type="number" class="form-control" id="stok" name="stok">
                  </div>
                </div>
              </div>
            </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success btn-sm">Save changes</button>
          </div>
          </form>
        </div>
      </div>
    </div>
    <!-- TAMBAH BARU  -->
</div>
@endsection